image-recreation:
  target-image-path: images\\mona-lisa-2.png
  shape:
    specifications:
      initial-size: 1
      delta: 1
      threshold: 100
    conversion-function: triangle

genetic-algorithm:
  population-size: 32
  mutation:
    rate: 0.5
  elitism-size: 4
  termination:
    time: 5m
